dist: bionic

language: C

before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq libcfitsio-dev libreadline6-dev libncurses5-dev libfftw3-dev libgsl0-dev flex bison

before_script:
- mkdir _build
- cd _build
- cmake ..

script:
- cmake ..
- make
- sudo make install
- sudo ln -s /usr/local/milk-1.1 /usr/local/milk
- export MILK_ROOT=${HOME}/src/milk
- export MILK_INSTALLDIR=/usr/local/milk
- export PATH=${PATH}:${MILK_INSTALLDIR}/bin
- export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:${MILK_INSTALLDIR}/lib/pkgconfig
- which milk
