dist: bionic

language: C

before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq libcfitsio-dev libreadline6-dev libncurses5-dev libfftw3-dev libgsl0-dev flex bison

before_script:
- mkdir _build
- cd _build
- cmake ..

script:
- cmake ..
- make
- sudo make install
- which milk
