dist: bionic

language: C

before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq libcfitsio-dev libreadline6-dev libncurses5-dev libfftw3-dev libgsl0-dev flex bison

before_script:
- echo "tmpfs /milk/shm tmpfs rw,nosuid,nodev" | sudo tee -a /etc/fstab
- sudo mkdir -p /milk/shm
- sudo mount /milk/shm
- export MILK_SHM_DIR=/milk/shm


script:
- mkdir _build
- cd _build
- cmake --version
- cmake .. -DEXTRAMODULES="milk_module_example" -DINSTALLMAKEDEFAULT=ON
- make
- sudo make install
- export MILK_ROOT=${HOME}/src/milk
- export MILK_INSTALLDIR=/usr/local/milk
- export PATH=${PATH}:${MILK_INSTALLDIR}/bin
- export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:${MILK_INSTALLDIR}/lib/pkgconfig
- ctest -D Experimental


