var dir_f5f134f34101966cba03a4b456ebe294 =
[
    [ "COREMOD_arith.c", "COREMOD__arith_8c.html", "COREMOD__arith_8c" ],
    [ "COREMOD_arith.h", "COREMOD__arith_8h_source.html", null ],
    [ "execute_arith.c", "execute__arith_8c.html", "execute__arith_8c" ],
    [ "execute_arith.h", "execute__arith_8h_source.html", null ],
    [ "image_arith__Cim_Cim__Cim.c", "image__arith____Cim__Cim____Cim_8c.html", "image__arith____Cim__Cim____Cim_8c" ],
    [ "image_arith__Cim_Cim__Cim.h", "image__arith____Cim__Cim____Cim_8h.html", "image__arith____Cim__Cim____Cim_8h" ],
    [ "image_arith__im__im.c", "image__arith____im____im_8c.html", "image__arith____im____im_8c" ],
    [ "image_arith__im__im.h", "image__arith____im____im_8h.html", "image__arith____im____im_8h" ],
    [ "image_arith__im_f__im.c", "image__arith____im__f____im_8c.html", "image__arith____im__f____im_8c" ],
    [ "image_arith__im_f__im.h", "image__arith____im__f____im_8h.html", "image__arith____im__f____im_8h" ],
    [ "image_arith__im_f_f__im.c", "image__arith____im__f__f____im_8c.html", "image__arith____im__f__f____im_8c" ],
    [ "image_arith__im_f_f__im.h", "image__arith____im__f__f____im_8h.html", "image__arith____im__f__f____im_8h" ],
    [ "image_arith__im_im__im.c", "image__arith____im__im____im_8c.html", "image__arith____im__im____im_8c" ],
    [ "image_arith__im_im__im.h", "image__arith____im__im____im_8h_source.html", null ],
    [ "image_crop.c", "image__crop_8c.html", "image__crop_8c" ],
    [ "image_crop.h", "image__crop_8h.html", "image__crop_8h" ],
    [ "image_dxdy.c", "image__dxdy_8c.html", "image__dxdy_8c" ],
    [ "image_dxdy.h", "image__dxdy_8h_source.html", null ],
    [ "image_merge3D.c", "image__merge3D_8c.html", "image__merge3D_8c" ],
    [ "image_merge3D.h", "image__merge3D_8h.html", "image__merge3D_8h" ],
    [ "image_stats.c", "COREMOD__arith_2image__stats_8c.html", "COREMOD__arith_2image__stats_8c" ],
    [ "image_stats.h", "COREMOD__arith_2image__stats_8h.html", "COREMOD__arith_2image__stats_8h" ],
    [ "image_total.c", "image__total_8c.html", "image__total_8c" ],
    [ "image_total.h", "image__total_8h.html", "image__total_8h" ],
    [ "imfunctions.c", "imfunctions_8c.html", "imfunctions_8c" ],
    [ "imfunctions.h", "imfunctions_8h_source.html", null ],
    [ "mathfuncs.c", "mathfuncs_8c.html", "mathfuncs_8c" ],
    [ "mathfuncs.h", "mathfuncs_8h.html", "mathfuncs_8h" ],
    [ "set_pixel.c", "set__pixel_8c.html", "set__pixel_8c" ],
    [ "set_pixel.h", "set__pixel_8h.html", "set__pixel_8h" ]
];