var dir_1fbe5abfc91f031908f9b0fcd26c05f0 =
[
    [ "DFT.c", "DFT_8c.html", "DFT_8c" ],
    [ "DFT.h", "DFT_8h.html", "DFT_8h" ],
    [ "dofft.c", "dofft_8c.html", "dofft_8c" ],
    [ "dofft.h", "dofft_8h.html", "dofft_8h" ],
    [ "fft.c", "fft_8c.html", "fft_8c" ],
    [ "fft.h", "fft_8h_source.html", null ],
    [ "fft_autocorrelation.c", "fft__autocorrelation_8c.html", "fft__autocorrelation_8c" ],
    [ "fft_autocorrelation.h", "fft__autocorrelation_8h.html", "fft__autocorrelation_8h" ],
    [ "fft_structure_function.c", "fft__structure__function_8c.html", "fft__structure__function_8c" ],
    [ "fft_structure_function.h", "fft__structure__function_8h.html", "fft__structure__function_8h" ],
    [ "fftcorrelation.c", "fftcorrelation_8c.html", "fftcorrelation_8c" ],
    [ "fftcorrelation.h", "fftcorrelation_8h_source.html", null ],
    [ "ffttranslate.c", "ffttranslate_8c.html", "ffttranslate_8c" ],
    [ "ffttranslate.h", "ffttranslate_8h.html", "ffttranslate_8h" ],
    [ "fftzoom.c", "fftzoom_8c.html", "fftzoom_8c" ],
    [ "fftzoom.h", "fftzoom_8h.html", "fftzoom_8h" ],
    [ "init_fftwplan.c", "init__fftwplan_8c.html", "init__fftwplan_8c" ],
    [ "init_fftwplan.h", "init__fftwplan_8h.html", "init__fftwplan_8h" ],
    [ "permut.c", "permut_8c.html", "permut_8c" ],
    [ "permut.h", "permut_8h.html", "permut_8h" ],
    [ "pupfft.c", "pupfft_8c.html", "pupfft_8c" ],
    [ "pupfft.h", "pupfft_8h.html", "pupfft_8h" ],
    [ "testfftspeed.c", "testfftspeed_8c.html", "testfftspeed_8c" ],
    [ "testfftspeed.h", "testfftspeed_8h.html", "testfftspeed_8h" ],
    [ "wisdom.c", "wisdom_8c.html", "wisdom_8c" ],
    [ "wisdom.h", "wisdom_8h.html", "wisdom_8h" ]
];