var dir_dca209fe662ec0d146440db0aa5b9932 =
[
    [ "Coeff2Map_Loop.c", "Coeff2Map__Loop_8c.html", null ],
    [ "Coeff2Map_Loop.h", "Coeff2Map__Loop_8h.html", null ],
    [ "cudacomp.c", "cudacomp_8c.html", "cudacomp_8c" ],
    [ "cudacomp.h", "cudacomp_8h.html", "cudacomp_8h" ],
    [ "cudacomp_MVMextractModesLoop.c", "cudacomp__MVMextractModesLoop_8c.html", "cudacomp__MVMextractModesLoop_8c" ],
    [ "cudacomp_MVMextractModesLoop.h", "cudacomp__MVMextractModesLoop_8h.html", null ],
    [ "cudacomp_types.h", "cudacomp__types_8h_source.html", null ],
    [ "cudacompinit.c", "cudacompinit_8c.html", null ],
    [ "cudacompinit.h", "cudacompinit_8h.html", null ],
    [ "cudacomptest.c", "cudacomptest_8c.html", null ],
    [ "cudacomptest.h", "cudacomptest_8h.html", null ],
    [ "GPU_loop_MultMat_execute.c", "GPU__loop__MultMat__execute_8c.html", null ],
    [ "GPU_loop_MultMat_execute.h", "GPU__loop__MultMat__execute_8h.html", null ],
    [ "GPU_loop_MultMat_free.c", "GPU__loop__MultMat__free_8c.html", null ],
    [ "GPU_loop_MultMat_free.h", "GPU__loop__MultMat__free_8h.html", null ],
    [ "GPU_loop_MultMat_setup.c", "GPU__loop__MultMat__setup_8c.html", null ],
    [ "GPU_loop_MultMat_setup.h", "GPU__loop__MultMat__setup_8h_source.html", null ],
    [ "GPU_SVD_computeControlMatrix.c", "GPU__SVD__computeControlMatrix_8c.html", null ],
    [ "GPU_SVD_computeControlMatrix.h", "GPU__SVD__computeControlMatrix_8h.html", null ],
    [ "GPUloadCmat.c", "GPUloadCmat_8c.html", null ],
    [ "GPUloadCmat.h", "GPUloadCmat_8h.html", null ],
    [ "magma_compute_SVDpseudoInverse.c", "magma__compute__SVDpseudoInverse_8c.html", null ],
    [ "magma_compute_SVDpseudoInverse.h", "magma__compute__SVDpseudoInverse_8h.html", null ],
    [ "magma_compute_SVDpseudoInverse_SVD.c", "magma__compute__SVDpseudoInverse__SVD_8c.html", null ],
    [ "magma_compute_SVDpseudoInverse_SVD.h", "magma__compute__SVDpseudoInverse__SVD_8h.html", null ],
    [ "MatMatMult_testPseudoInverse.c", "MatMatMult__testPseudoInverse_8c.html", null ],
    [ "MatMatMult_testPseudoInverse.h", "MatMatMult__testPseudoInverse_8h_source.html", null ],
    [ "MVM_CPU.c", "MVM__CPU_8c.html", "MVM__CPU_8c" ],
    [ "MVM_CPU.h", "MVM__CPU_8h.html", "MVM__CPU_8h" ],
    [ "printGPUMATMULTCONF.c", "printGPUMATMULTCONF_8c.html", null ],
    [ "printGPUMATMULTCONF.h", "printGPUMATMULTCONF_8h.html", null ]
];