#!/usr/bin/env bash


MSdescr="Simple function test"

scriptname=$(basename $0)

MSextdescr="Simple function test

Computes image total"


source milk-script-std-config

RequiredCommands=(milk)
RequiredFiles=()
RequiredDirs=()

source milk-argparse


milk << EOF

# create images imd1 and imd2
imgen.mkdisk imd1 256 256 128 128 50
imgen.mkdisk imd2 256 256 128 128 10

# load module
mload milkmilkmoduleexample
m? milk_module_example

# change scaling
modex.simplefuncFPS .scaling 0.31
modex.simplefuncFPS .in_name imd1

# print function help
cmd? modex.simplefuncFPS

# list images in memory
listim

# Create/initialize FPS if it does not exist
# Default FPS name is function key without namespace.
# Arguments following _FPSINIT_ are pasted to construct
# the FPS name.
# If FPS already exists, do nothing (param values
# may then be out of sync)
modex.simplefuncFPS _FPSINIT_ "03"

modex.simplefuncFPS .scaling 0.5
modex.simplefuncFPS _FPSINIT_ "05"

# FPS call, uses last active FPS name
modex.simplefuncFPS _RUNSTART_

# add arg to specify which FPS to use
modex.simplefuncFPS _RUNSTART_ "03"
modex.simplefuncFPS _RUNSTART_ "05"

# non-FPS call
# changing argument value does not change FPS
modex.simplefuncFPS .scaling 1.0
modex.simplefuncFPS imd1


# change scaling parameter for function
modex.simplefuncFPS .scaling 0.3

# run again
modex.simplefuncFPS .

exitCLI
EOF

